version: "3"
services:
  apollo-server:
    build: ./apolloserver
 
  nginx:
    build: 
      context: .
      dockerfile: ./webserver/Dockerfile
    restart: always
    ports:
      - "80:80"
    environment:
      - VITE_API_KEY=$VITE_API_KEY
      - VITE_AUTH_DOMAIN=$VITE_AUTH_DOMAIN
      - VITE_PROJECT_ID=$VITE_PROJECT_ID
      - VITE_STORAGE_BUCKET=$VITE_STORAGE_BUCKET
      - VITE_MESSAGING_SENDER_ID=$VITE_MESSAGING_SENDER_ID
      - VITE_APP_ID=$VITE_APP_ID
    
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD

