version: "3"
services:
  api:
    image: $DOCKERHUB_UNAME/pokemon-ts-graphql_api-prod:$NEW_VERSION 
    ports:
      - "4000:4000"
    environment:
      - DB_NAME=$POSTGRES_DB
      - DB_USER=$POSTGRES_USER
      - DB_PASS=$POSTGRES_PASSWORD
    depends_on:
      - db
  nginx:
    image: $DOCKERHUB_UNAME/pokemon-ts-graphql_api-prod:$NEW_VERSION
    restart: always
    ports:
      - "80:80"
    environment:
      - VITE_API_KEY=$VITE_API_KEY
      - VITE_AUTH_DOMAIN=$VITE_AUTH_DOMAIN
      - VITE_PROJECT_ID=$VITE_PROJECT_ID
      - VITE_STORAGE_BUCKET=$VITE_STORAGE_BUCKET
      - VITE_MESSAGING_SENDER_ID=$VITE_MESSAGING_SENDER_ID
      - VITE_APP_ID=$VITE_APP_ID
      - FIREBASE_AUTH_DOMAIN=$FIREBASE_AUTH_DOMAIN
    
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD

